title: Czarina Jane Ochoa
#logo: /img/character.jpg
#description: 
show_downloads: true
github:
  zip_url: /img/CzarinaJaneOchoa.pdf
  tar_url: czarinajane.ochoa17@gmail.com
theme: jekyll-theme-minimal
